
geodes_lib:register_geode({
    id = 'mese_1',
    wherein = "default:stone",
    y_min = -11000,
    y_max = -7000,
    scarcity = 77,
    generation_chance = 50,
    inner = "mese_rift:mese_crystal",
    inners = {{ name = "amethyst_new:calcite", fill = 30 }, { name = "ctg_quartz:quartz", fill = 47 }, { name = "mese_rift:mese_crystal", fill = 13 },},
    inner_alt = {"mese_rift:mese_crystal_budding", "ctg_quartz:quartz_budding"},
    inner_alt_chance = 50,
    shell = {"amethyst_new:basalt", "amethyst_new:basalt", "amethyst_new:calcite", "amethyst_new:calcite", "ctg_quartz:quartz"},
    cavity = { lower_fill = "default:lava_source", upper_fill = "air", threshold = 20, span = 20 },
    radius_min = 3,
    radius_max = 8,
})
geodes_lib:register_geode({
    id = 'mese_1_corestone',
    wherein = "ctg_world:corestone",
    y_min = -11000,
    y_max = -9000,
    scarcity = 75,
    generation_chance = 70,
    inner = "mese_rift:mese_crystal",
    inners = {{ name = "amethyst_new:calcite", fill = 30 }, { name = "ctg_quartz:quartz", fill = 47 }, { name = "mese_rift:mese_crystal", fill = 13 },},
    inner_alt = {"mese_rift:mese_crystal_budding", "ctg_quartz:quartz_budding"},
    inner_alt_chance = 40,
    shell = {"amethyst_new:basalt", "amethyst_new:basalt", "amethyst_new:calcite", "amethyst_new:calcite", "ctg_quartz:quartz"},
    cavity = { lower_fill = "default:lava_source", upper_fill = "air", threshold = 20, span = 20 },
    radius_min = 3,
    radius_max = 8,
})

geodes_lib:register_geode({
    id = 'mese_2',
    wherein = "default:stone",
    y_min = -7000,
    y_max = -3000,
    scarcity = 80,
    generation_chance = 20,
    inner = "mese_rift:mese_crystal",
    inners = {{ name = "amethyst_new:calcite", fill = 28 }, { name = "ctg_quartz:quartz", fill = 42 }, { name = "mese_rift:mese_crystal", fill = 5 },},
    inner_alt = {"mese_rift:mese_crystal_budding", "ctg_quartz:quartz_budding"},
    inner_alt_chance = 100,
    shell = {"amethyst_new:basalt", "amethyst_new:basalt", "amethyst_new:calcite", "amethyst_new:calcite"},
    cavity = { lower_fill = "default:river_water_source", upper_fill = "air", threshold = 36, span = 35 },
    radius_min = 2,
    radius_max = 7,
})
